name: Build & Deploy Angular
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/dcucountdown/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: frontend/dcucountdown
      
      - name: Build Angular app
        run: npm run build -- --base-href=/DCU-countdown/
        working-directory: frontend/dcucountdown
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dcucountdown/dist/dcucountdown/browser
          cname: 
